// Package render turns a gssh config into an ssh_config fragment and wires it
// into the user's ~/.ssh/config via an Include directive.
package render

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/clveryang/gssh/internal/model"
)

const (
	// BeginMarker/EndMarker delimit the block gssh owns in ~/.ssh/config.
	BeginMarker = "# >>> gssh >>>"
	EndMarker   = "# <<< gssh <<<"

	header = `# GENERATED BY gssh -- DO NOT EDIT
# Source: %s
# Regenerate with: gssh sync
# Written: %s

`
)

// FragmentPath is where the generated ssh_config fragment lives.
// GSSH_FRAGMENT overrides it, which is what the tests use.
func FragmentPath() string {
	if p := os.Getenv("GSSH_FRAGMENT"); p != "" {
		return p
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".ssh", "config.d", "gssh.conf")
}

// SSHConfigPath is the user's main ssh config. GSSH_SSH_CONFIG overrides it.
func SSHConfigPath() string {
	if p := os.Getenv("GSSH_SSH_CONFIG"); p != "" {
		return p
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".ssh", "config")
}

// Fragment renders the whole config as an ssh_config file body.
func Fragment(c *model.Config, sourcePath string) string {
	var b strings.Builder
	fmt.Fprintf(&b, header, sourcePath, time.Now().Format(time.RFC3339))

	var lastGroup string
	for _, h := range c.AllHosts() {
		if h.Group != lastGroup {
			if h.Group != "" {
				fmt.Fprintf(&b, "# ---- %s ----\n", h.Group)
			}
			lastGroup = h.Group
		}
		writeHost(&b, h, c.Defaults)
	}
	return b.String()
}

func writeHost(b *strings.Builder, h *model.Host, defaults model.Options) {
	if !model.SSHSafe(h.Name) {
		// ssh rejects this name, so the block is keyed on an ASCII one.
		fmt.Fprintf(b, "# %s  (ssh %s)\n", h.Name, h.Target())
	}
	if h.Note != "" {
		fmt.Fprintf(b, "# %s\n", h.Note)
	}
	var names []string
	seen := map[string]bool{}
	for _, n := range append([]string{h.Target(), h.Name}, h.Alias...) {
		if model.SSHSafe(n) && !seen[n] {
			seen[n] = true
			names = append(names, n)
		}
	}
	fmt.Fprintf(b, "Host %s\n", strings.Join(names, " "))
	kv(b, "HostName", h.Host)

	o := merge(h.Options, defaults)
	kv(b, "User", o.User)
	if o.Port != 0 {
		kv(b, "Port", fmt.Sprint(o.Port))
	}
	kv(b, "IdentityFile", o.IdentityFile)
	kv(b, "ProxyJump", o.ProxyJump)
	if o.ForwardAgent != nil {
		kv(b, "ForwardAgent", yesno(*o.ForwardAgent))
	}
	if o.ServerAliveInterval != 0 {
		kv(b, "ServerAliveInterval", fmt.Sprint(o.ServerAliveInterval))
	}
	if o.ServerAliveCountMax != 0 {
		kv(b, "ServerAliveCountMax", fmt.Sprint(o.ServerAliveCountMax))
	}
	for _, f := range o.LocalForward {
		kv(b, "LocalForward", f)
	}
	for _, f := range o.RemoteForward {
		kv(b, "RemoteForward", f)
	}
	for _, f := range o.DynamicForward {
		kv(b, "DynamicForward", f)
	}
	for _, k := range sortedKeys(o.Raw) {
		kv(b, k, o.Raw[k])
	}
	b.WriteString("\n")
}

// merge fills unset fields of a from d. Slices and Raw are concatenated so a
// per-host LocalForward adds to, rather than replaces, a global one.
func merge(a, d model.Options) model.Options {
	if a.User == "" {
		a.User = d.User
	}
	if a.Port == 0 {
		a.Port = d.Port
	}
	if a.IdentityFile == "" {
		a.IdentityFile = d.IdentityFile
	}
	if a.ProxyJump == "" {
		a.ProxyJump = d.ProxyJump
	}
	if a.ForwardAgent == nil {
		a.ForwardAgent = d.ForwardAgent
	}
	if a.ServerAliveInterval == 0 {
		a.ServerAliveInterval = d.ServerAliveInterval
	}
	if a.ServerAliveCountMax == 0 {
		a.ServerAliveCountMax = d.ServerAliveCountMax
	}
	a.LocalForward = append(append([]string{}, d.LocalForward...), a.LocalForward...)
	a.RemoteForward = append(append([]string{}, d.RemoteForward...), a.RemoteForward...)
	a.DynamicForward = append(append([]string{}, d.DynamicForward...), a.DynamicForward...)
	if len(d.Raw) > 0 {
		raw := make(map[string]string, len(d.Raw)+len(a.Raw))
		for k, v := range d.Raw {
			raw[k] = v
		}
		for k, v := range a.Raw {
			raw[k] = v
		}
		a.Raw = raw
	}
	return a
}

func kv(b *strings.Builder, key, val string) {
	if val == "" {
		return
	}
	fmt.Fprintf(b, "    %s %s\n", key, val)
}

func yesno(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	// Small maps; insertion sort keeps output stable without importing sort.
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j] < out[j-1]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

var includeRe = regexp.MustCompile(`(?i)^\s*Include\s`)

// EnsureInclude adds the gssh Include block to ~/.ssh/config if absent, placing
// it after any leading Include lines (so tools like colima keep their
// precedence) but before the first Host block (so gssh definitions win over
// hand-written duplicates left behind after an import).
//
// It is idempotent and returns true when the file was modified.
func EnsureInclude(sshConfig, fragment string) (bool, error) {
	data, err := os.ReadFile(sshConfig)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	body := string(data)
	if strings.Contains(body, BeginMarker) {
		return false, nil
	}

	block := fmt.Sprintf("%s\nInclude %s\n%s\n", BeginMarker, tildify(fragment), EndMarker)
	if strings.TrimSpace(body) == "" {
		return true, writeFile(sshConfig, block)
	}

	lines := splitLines(body)
	insert := 0
	for i, ln := range lines {
		t := strings.TrimSpace(ln)
		if t == "" || strings.HasPrefix(t, "#") {
			continue
		}
		if includeRe.MatchString(ln) {
			insert = i + 1
			continue
		}
		break // first real directive (Host/Match/keyword) -- stop here
	}

	out := make([]string, 0, len(lines)+4)
	out = append(out, lines[:insert]...)
	if insert > 0 {
		out = append(out, "")
	}
	out = append(out, strings.TrimRight(block, "\n"), "")
	out = append(out, lines[insert:]...)
	return true, writeFile(sshConfig, strings.Join(out, "\n"))
}

func splitLines(s string) []string {
	var out []string
	sc := bufio.NewScanner(strings.NewReader(s))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		out = append(out, sc.Text())
	}
	return out
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o600)
}

// WriteFragment writes the generated fragment to disk.
func WriteFragment(path, content string) error {
	return writeFile(path, content)
}

func tildify(p string) string {
	home, err := os.UserHomeDir()
	if err != nil || !strings.HasPrefix(p, home+string(filepath.Separator)) {
		return p
	}
	return "~" + p[len(home):]
}
